### ISSUE TITLE
Refractoring Point class

### ISSUE THREAD

**Issue by droni1234** [MatijaBrown/SilkyNvg#1]
I would like to add a lot more overloaded methods,
aswell as overloading operators for :
- sum
- substraction
- equality

I would also rename tol to eps (short for epsilon or also precision value called)
I think eps would be understood better 
and add a default value like 1e-6

Add some documentation explaining, what
- dmx
- dm
- length
does later on

```cs
        public bool IsCorner();
        public bool IsLeft();
        public bool IsBevel();
        public bool IsInnerbevel();
```
I would consider putting these methods outside, but I am not sure about this one.
It would make the class little bit cleaner
```cs
        public bool IsCorner(Point p);
        public bool IsLeft(Point p);
        public bool IsBevel(Point p);
        public bool IsInnerbevel(Point p);
```

**Comment by MatijaBrown** [comment]
How about making the IsCorner(Point point) methods static?

**Comment by droni1234** [comment]
Of course, I played with the idea, that the class does not have to be part of the Point class. But sure let us go static for now
