### ISSUE TITLE
Why not consider using C# libraries such as https://github.com/LayoutFarm/Typography for font reading and drawing Text.

### ISSUE THREAD

**Issue by sgf** [MatijaBrown/SilkyNvg#10]
Why not consider using C# libraries such as https://github.com/LayoutFarm/Typography for font reading and drawing. In the long run, relying on libraries such as C/C++/Rust is not conducive to the development of C#'s own open source ecosystem.

Even though the existing C# libraries are very imperfect, at least every use is an opportunity to improve them. Only by using these libraries can we find the missing parts, make up for them, and improve and develop them.

**Comment by MatijaBrown** [comment]
You are right that I am looking for a replacement to my garbage heap called _FontStash.NET_. I'll check out [Typography](https://github.com/LayoutFarm/Typography) certainly!
Keep in mind though: It would need to only handle the loading and sending draw calls - the rendering shall and must be done via the already existing rendering pipeline to allow for easy implementation of a custom rendering engine if so desired (for example if you wanted DirectX - one day I'll get around to supplying one, but that day is not today unfortunately 😢).
However, thank you for the suggestion - that is the next thing on the list after Svg Support. It would likely also involve adding support for more font formats than the current TrueType.

**Comment by sgf** [comment]
Of course, we have to admit that C# is really lacking in these infrastructures. It's great that you can consider it, but if you don't  choice it in the end, don't mind it too much. After all, if time is running out, people can choose wapper. After all, compared with work, perfecting open source libraries is not worth mentioning.
