### ISSUE TITLE
Can SilkyNvg be a replacement for SkiaSharp? 

### ISSUE THREAD

**Issue by sgf** [MatijaBrown/SilkyNvg#9]
The SkiaSharp dll file is too large, close to 10mb.
I'm looking for a 2d graphics library developed in pure C#

**Comment by MatijaBrown** [comment]
If you are using a GPU-Interface like OpenGL or Vulkan, certainly yes. Keep in mind though; it hasen't got any own scene graph elements - it's merely a Vector Graphics Rendering library - specifically a port of NanoVG.
So if you want to draw stuff on a Vulkan Window or OpenGL window - use it. If you want stuff like Text Input dialoges, then it's likely not a good option. Basically, it is a port of [NanoVG](https://github.com/memononen/nanovg).
I do want to build a proper scene-graphed UI library from it, but that is in the far far future and far far away.

**Comment by sgf** [comment]
OK, thank you for your reply. This way, I have a clearer understanding of this library.
